### ISSUE TITLE
Binary release is missing ssleay32.dll

### ISSUE THREAD

**Issue by thfr** [kriswebdev/encfs4win-reloaded#1]
Hi,

thanks for providing an updated version of EncFS4Win! I tested the binaries and the program failed to start stating that `ssleay32.dll` is missing. After copying `ssleay32.dll` in the program folder or installing OpenSSL-Win32, the program worked. Maybe you should include `ssleay32.dll` in your binary release.

**Comment by kriswebdev** [comment]
Thanks for poiting this out. Indeed, OpenSSL project renamed libssl32.dll to ssleay32.dll.
Strange enough, I didn't faced this issue using the mispelled dll and without OpenSSL-Win32 installed.

This is now solved. I just renamed the file in the binary distribution and the references in the project files.
