### ISSUE TITLE
 MSVCP120.dll is missing error on Win7

### ISSUE THREAD

**Issue by tlvu** [kriswebdev/encfs4win-reloaded#4]
I installed the Visual C++ Redistributable Packages for Visual Studio 2013 https://www.microsoft.com/en-ca/download/details.aspx?id=40784 (instead of 2015) as mentionned in the README and it fixed the problem.

Is this expected?

**Comment by kriswebdev** [comment]
Hi @tlvu,

Visual C++ Redistributable Packages for Visual Studio **2013** is a pre-requisite of Dokany 0.7.4.
I admit it's not mentioned on the release link provided, but it's mentioned in Dokany README page.

Visual C++ Redistributable Packages for Visual Studio **2015** is a pre-requisite for Encfs4Win Reloaded on Windows 7. I noticed that it's not necessary on Windows 10. I don't really know why.

I'll update the README.

**Comment by tlvu** [comment]
@kriswebdev Thanks !  The 2013 was indeed for Dokany not encfs4-win.  I did saw Dokany installer mention about  a "Visual C++ Redistributable Packages for Visual Studio" but I read to fast and did not notice 2013 so I thought it was the same version 2015 that I already installed.
